spring:
  application:
    name: USER-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: USER-CONSUMER
        uri: lb://USER-CONSUMER/
        predicates:
          - Path=/consume/**
      - id: USER-PRODUCER
        uri: lb://USER-PRODUCER/
        predicates:
          - Path=/produce/**
    discovery:
      locator:
        enabled: true

      reactive:
        enabled: false

server:
  port: 8090
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true

